version: "3.1"
services:
  web:
    build: ./
    ports:
    - 80:80
    restart: always
    volumes:
    - webapp_data:/usr/share/nginx/html
    networks:
      - frontend

volumes:
  webapp_data:

networks:
  frontend:
    driver: bridge
